# Generated by Django 4.1.1 on 2022-10-06 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0002_remove_student_num_users_student_disability"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="num_users",
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
