# Generated by Django 4.1.1 on 2022-10-09 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0003_student_num_users"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="disability",
        ),
    ]
