name: 'First interaction'

on:
  pull_request_target:
    types: [opened]
    
jobs:
  welcome:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/first-interaction@v1.0.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          pr-message: |-
            Congratulations on making your first Pull Request and thanks for taking the time to improve Care-Craft! ♥
